export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_SETUSUARIO = "LOGIN_SETUSUARIO";
export const LOGIN_AGENDA = "LOGIN_AGENDA";

export const USUARIOROL_LOADING = "USUARIOROL_LOADING";
export const USUARIOROL_SUCCESS = "USUARIOROL_SUCCESS";
export const USUARIOROL_ITEMEDITADO = "USUARIOROL_ITEMEDITADO";
export const USUARIOROL_ERROR = "USUARIOROL_ERROR";

export const TEXTOS_LOADING = "TEXTOS_LOADING";
export const TEXTOS_SUCCESS = "TEXTOS_SUCCESS";
export const TEXTOS_ERROR = "TEXTOS_ERROR";
export const TEXTOS_RESET = "TEXTOS_RESET";

export const CHANGE_MODE = "CHANGE_MODE";

export const MODAL_HIDE = "MODAL_HIDE";
export const MODAL_SHOW = "MODAL_SHOW";

export const SEGUNDOMODAL_HIDE = "SEGUNDOMODAL_HIDE";
export const SEGUNDOMODAL_SHOW = "SEGUNDOMODAL_SHOW";

export const TOASTER_HIDE = "TOASTER_HIDE";
export const TOASTER_SHOW = "TOASTER_SHOW";

export const TOKEN_VALIDATION = "TOKEN_VALIDATION";
export const TOKEN_VALIDATION_SUCCESS = "TOKEN_VALIDATION_SUCCESS";
export const TOKEN_VALIDATION_FAIL = "TOKEN_VALIDATION_FAIL";

export const JSONCONFIG_SUCCESS = "JSONCONFIG_SUCCESS";

export const TOKEN_LOADING = "TOKEN_LOADING";
export const TOKEN_SUCCESS = "TOKEN_SUCCESS";
export const TOKEN_ERROR = "TOKEN_ERROR";
export const TOKEN_LOGOUT = "TOKEN_LOGOUT";

export const VERSION_PUBLICADA_LOADING = "VERSION_PUBLICADA_LOADING";
export const VERSION_PUBLICADA_SUCCESS = "VERSION_PUBLICADA_SUCCESS";
export const VERSION_PUBLICADA_ERROR = "VERSION_PUBLICADA_ERROR";
export const VERSION_PUBLICADA_RESET = "VERSION_PUBLICADA_RESET";

export const RESET_GLOBAL_CONTEXT = "RESET_GLOBAL_CONTEXT";
