export const GET_ABM = "GET_ABM";
export const GET_ABM_SUCCESS = "GET_ABM_SUCCESS";
export const GET_ABM_FAIL = "GET_ABM_FAIL";

export const POST_ABM = "POST_ABM";
export const POST_ABM_SUCCESS = "POST_ABM_SUCCESS";
export const POST_ABM_FAIL = "POST_ABM_FAIL";

export const PUT_ABM = "PUT_ABM";
export const PUT_ABM_SUCCESS = "PUT_ABM_SUCCESS";
export const PUT_ABM_FAIL = "PUT_ABM_FAIL";

export const DELETE_ABM = "DELETE_ABM";
export const DELETE_ABM_SUCCESS = "DELETE_ABM_SUCCESS";
export const DELETE_ABM_FAIL = "DELETE_ABM_FAIL";

export const SELECTED_ITEM = "SELECTED_ITEM";
export const ALL_SELECTED_ITEM = "ALL_SELECTED_ITEM";

export const PACIENTE_LOADING = "PACIENTE_LOADING";
export const PACIENTE_ERROR = "PACIENTE_ERROR";
export const PACIENTE_BUSCARPAC = "PACIENTE_BUSCARPAC";
export const PACIENTE_SETPACIENTEBUSQ = "PACIENTE_SETPACIENTEBUSQ";
export const PACIENTE_ESTUDIOS = "PACIENTE_ESTUDIOS";
export const PACIENTE_INFORMES = "PACIENTE_INFORMES";
export const PACIENTE_DATOCONFIDENCIAL = "PACIENTE_DATOCONFIDENCIAL";
export const PACIENTE_INFHISTORICO = "PACIENTE_INFHISTORICO";
export const PACIENTE_RESET = "PACIENTE_RESET";
export const PACIENTE_RESETESTUDIOS = "PACIENTE_RESETESTUDIOS";
export const PACIENTE_RESETINFORMES = "PACIENTE_RESETINFORMES";
export const PACIENTE_RESET_INFHISTORICO = "PACIENTE_RESET_INFHISTORICO";
export const PACIENTE_SETESTUDIOS = "PACIENTE_SETESTUDIOS";
export const PACIENTE_SETINFHISTORICO = "PACIENTE_SETINFHISTORICO";
export const PACIENTE_SETINFORMES = "PACIENTE_SETINFORMES";
export const PACIENTE_SETDATOCONFIDENCIAL = "PACIENTE_SETDATOCONFIDENCIAL";

export const EVOLUCION_LOADING = "EVOLUCION_LOADING";
export const EVOLUCION_ERROR = "EVOLUCION_ERROR";
export const EVOLUCION_GUARDAREVO = "EVOLUCION_GUARDAREVO";
export const EVOLUCION_PREIMPRESION = "EVOLUCION_PREIMPRESION";
export const EVOLUCION_DATOS = "EVOLUCION_DATOS";
export const EVOLUCION_HISTORICAS = "EVOLUCION_HISTORICAS";
export const EVOLUCION_FILTROSTL = "EVOLUCION_FILTROSTL";
export const EVOLUCION_SETFILTROSTL = "EVOLUCION_SETFILTROSTL";
export const EVOLUCION_HCXPDF = "EVOLUCION_HCXPDF";
export const EVOLUCION_EDITAEVO = "EVOLUCION_EDITAEVO";
export const EVOLUCION_RESETEDITAEVO = "EVOLUCION_RESETEDITAEVO";
export const EVOLUCION_CREARHTML = "EVOLUCION_CREARHTML";
export const EVOLUCION_RESETEVO = "EVOLUCION_RESETEVO";
export const EVOLUCION_RESETGUARDAREVO = "EVOLUCION_RESETGUARDAREVO";
export const EVOLUCION_RESET = "EVOLUCION_RESET";
export const EVOLUCION_RESETHISTORICAS = "EVOLUCION_RESETHISTORICAS";
export const EVOLUCION_SETHISTORICAS = "EVOLUCION_SETHISTORICAS";
export const EVOLUCION_RESET_DATOS = "EVOLUCION_RESET_DATOS";
export const EVOLUCION_RESETHCXPDF = "EVOLUCION_RESETHCXPDF";
export const EVOLUCION_RESETPREIMPRESION = "EVOLUCION_RESETPREIMPRESION";

export const LABORATORIO_LOADING = "LABORATORIO_LOADING";
export const LABORATORIO_ERROR = "LABORATORIO_ERROR";
export const LABORATORIO_LABNOMENCLADOR = "LABORATORIO_LABNOMENCLADOR";
export const LABORATORIO_ITEMSORDENHC = "LABORATORIO_ITEMSORDENHC";
export const LABORATORIO_GRUPOESTUDIOSUSUARIO =
  "LABORATORIO_GRUPOESTUDIOSUSUARIO";
export const LABORATORIO_GRUPOESTUDIOS = "LABORATORIO_GRUPOESTUDIOS";
export const LABORATORIO_HISTORICO = "LABORATORIO_HISTORICO";
export const LABORATORIO_PDF = "LABORATORIO_PDF";
export const LABORATORIO_RESETPDF = "LABORATORIO_RESETPDF";
export const LABORATORIO_RESETHISTORICO = "LABORATORIO_RESETHISTORICO";
export const LABORATORIO_RESET = "LABORATORIO_RESET";
export const LABORATORIO_RESETPARCIAL = "LABORATORIO_RESETPARCIAL";
export const LABORATORIO_GUARDARORDEN = "LABORATORIO_GUARDARORDEN";
export const LABORATORIO_SETGRUPOESTUDIOSUSUARIO =
  "LABORATORIO_SETGRUPOESTUDIOSUSUARIO";
export const LABORATORIO_SETGRUPOESTUDIOS = "LABORATORIO_SETGRUPOESTUDIOS";
export const LABORATORIO_SETITEMSORDENHC = "LABORATORIO_SETITEMSORDENHC";
export const LABORATORIO_SETLABNOMENCLADOR = "LABORATORIO_SETLABNOMENCLADOR";
export const LABORATORIO_SETHISTORICO = "LABORATORIO_SETHISTORICO";
export const LABORATORIO_INFORMESTRING = "LABORATORIO_INFORMESTRING";
export const LABORATORIO_INFORMEANORMAL = "LABORATORIO_INFORMEANORMAL";
// Nuevos action types para la página de laboratorio
export const LABORATORIO_LABORATORIOSPACIENTE =
  "LABORATORIO_LABORATORIOSPACIENTE";
export const LABORATORIO_DATOSGRAFICO = "LABORATORIO_DATOSGRAFICO";
export const LABORATORIO_COLUMNASGRAFICO = "LABORATORIO_COLUMNASGRAFICO";
export const LABORATORIO_FILASGRAFICO = "LABORATORIO_FILASGRAFICO";
export const LABORATORIO_ESTUDIOSGRAFICO = "LABORATORIO_ESTUDIOSGRAFICO";
export const LABORATORIO_RESETINFORME = "LABORATORIO_RESETINFORME";

export const ABREVIATURA_LOADING = "ABREVIATURA_LOADING";
export const ABREVIATURA_ERROR = "ABREVIATURA_ERROR";
export const ABREVIATURA_SUCCESS = "ABREVIATURA_SUCCESS";

export const MEDICAMENTO_LOADING = "MEDICAMENTO_LOADING";
export const MEDICAMENTO_ERROR = "MEDICAMENTO_ERROR";
export const MEDICAMENTO_SUCCESS = "MEDICAMENTO_SUCCESS";
export const MEDICAMENTO_RESET = "MEDICAMENTO_RESET";

export const ESTUDIO_LOADING = "ESTUDIO_LOADING";
export const ESTUDIO_ERROR = "ESTUDIO_ERROR";
export const ESTUDIO_SUCCESS = "ESTUDIO_SUCCESS";
export const ESTUDIO_RESET = "ESTUDIO_RESET";

export const TIPOS_LOADING = "TIPOS_LOADING";
export const TIPOS_ERROR = "TIPOS_ERROR";
export const TIPOS_SUCCESS = "TIPOS_SUCCESS";

export const DIAGNOSTICO_LOADING = "DIAGNOSTICO_LOADING";
export const DIAGNOSTICO_ERROR = "DIAGNOSTICO_ERROR";
export const DIAGNOSTICO_SUCCESS = "DIAGNOSTICO_SUCCESS";
export const DIAGNOSTICO_SETDATA = "DIAGNOSTICO_SETDATA";
export const DIAGBYNAME_SUCCESS = "DIAGBYNAME_SUCCESS";
export const DIAGBYNAME_SETDATA = "DIAGBYNAME_SETDATA";

export const SEGUIMIENTO_LOADING = "SEGUIMIENTO_LOADING";
export const SEGUIMIENTO_ERROR = "SEGUIMIENTO_ERROR";
export const SEGUIMIENTO_SUCCESS = "SEGUIMIENTO_SUCCESS";
export const SEGUIMIENTO_IDPAC = "SEGUIMIENTO_IDPAC";
export const SEGUIMIENTO_ALL = "SEGUIMIENTO_ALL";
export const SEGUIMIENTO_SAVE = "SEGUIMIENTO_SAVE";
export const SEGUIMIENTO_EDIT = "SEGUIMIENTO_EDIT";
export const SEGUIMIENTO_EVENTXID = "SEGUIMIENTO_EVENTXID";
export const SEGUIMIENTO_EVENTSAVE = "SEGUIMIENTO_EVENTSAVE";
export const SEGUIMIENTO_UPDATEXID = "SEGUIMIENTO_UPDATEXID";
export const SEGUIMIENTO_SETSEGALL = "SEGUIMIENTO_SETSEGALL";
export const RESET_EVENTXID = "RESET_EVENTXID";
export const RESET_SEGCTX = "RESET_SEGCTX";
export const RESET_SEGIDPAC = "RESET_SEGIDPAC";

export const SNOMED_LOADING = "SNOMED_LOADING";
export const SNOMED_ERROR = "SNOMED_ERROR";
export const SNOMED_FSNITEM = "SNOMED_FSNITEM";
export const SNOMED_RESETDATA = "SNOMED_RESETDATA";

export const INFORME_LOADING = "INFORME_LOADING";
export const INFORME_ERROR = "INFORME_ERROR";
export const INFORME_INFORMEPDF = "INFORME_INFORMEPDF";
export const INFORME_VISORES = "INFORME_VISORES";
export const INFORME_RESETVISOR = "INFORME_RESETVISOR";
export const INFORME_RESETINFORMEPDF = "INFORME_RESETINFORMEPDF";
export const INFORME_RESET = "INFORME_RESET";

export const ORDENPRACTICA_LOADING = "ORDENPRACTICA_LOADING";
export const ORDENPRACTICA_ERROR = "ORDENPRACTICA_ERROR";
export const ORDENPRACTICA_SUCCESS = "ORDENPRACTICA_SUCCESS";
export const ORDENPRACTICA_XESP = "ORDENPRACTICA_XESP";
export const ORDENPRACTICA_SETORDENPRACXMED = "ORDENPRACTICA_SETORDENPRACXMED";
export const ORDENPRACTICA_RESETXESP = "ORDENPRACTICA_RESETXESP";
export const ORDENPRACTICA_XUSER = "ORDENPRACTICA_XUSER";
export const ORDENPRACTICA_SETORDENPRACXUSR = "ORDENPRACTICA_SETORDENPRACXUSR";
export const ORDENPRACTICA_RESETXUSER = "ORDENPRACTICA_RESETXUSER";
export const ORDENPRACTICA_GUARDARPRAC = "ORDENPRACTICA_GUARDARPRAC";
export const ORDENPRACTICA_RESET = "ORDENPRACTICA_RESET";
export const ORDENPRACTICA_RESETERROR = "ORDENPRACTICA_RESETERROR";
export const ORDENPRACTICA_ESTUDIOGRUPO = "ORDENPRACTICA_ESTUDIOGRUPO";
export const ORDENPRACTICA_SETESTUDIOGRUPO = "ORDENPRACTICA_SETESTUDIOGRUPO";

export const EXAMEN_LOADING = "EXAMEN_LOADING";
export const EXAMEN_SUCCESS = "EXAMEN_SUCCESS";
export const EXAMEN_ERROR = "EXAMEN_ERROR";
export const EXAMEN_RESET = "EXAMEN_RESET";
export const EXAMEN_SETCONTEXT = "EXAMEN_SETCONTEXT";

export const VADEMECUM_LOADING = "VADEMECUM_LOADING";
export const VADEMECUM_SUCCESS = "VADEMECUM_SUCCESS";
export const VADEMECUM_ERROR = "VADEMECUM_ERROR";
export const VADEMECUM_TIPO = "VADEMECUM_TIPO";
export const VADEMECUMBYID_LOADING = "VADEMECUMBYID_LOADING";
export const VADEMECUMBYID_SUCCESS = "VADEMECUMBYID_SUCCESS";
export const VADEMECUMBYID_ERROR = "VADEMECUMBYID_ERROR";
export const VADEMECUMBYID_RESET = "VADEMECUMBYID_RESET";
export const VADEMECUM_RESET = "VADEMECUM_RESET";

export const AUDITORIA_LOADING = "AUDITORIA_LOADING";
export const AUDITORIA_ERROR = "AUDITORIA_ERROR";
export const AUDITORIA_MANUALES = "AUDITORIA_MANUALES";
export const AUDITORIA_SETMANUALES = "AUDITORIA_SETMANUALES";

export const AUDITSNOMED_LOADING = "AUDITSNOMED_LOADING";
export const AUDITSNOMED_ERROR = "AUDITSNOMED_ERROR";
export const AUDITSNOMED_TABLELISTOK = "AUDITSNOMED_TABLELISTOK";
export const AUDITSNOMED_SETDATATABLE = "AUDITSNOMED_SETDATATABLE";
export const AUDITSNOMED_REEMPLAZAROK = "AUDITSNOMED_REEMPLAZAROK";
export const AUDITSNOMED_RESETAFTEREDIT = "AUDITSNOMED_RESETAFTEREDIT";
export const AUDITSNOMED_EVOHTML = "AUDITSNOMED_EVOHTML";

export const RECETADIGITAL_LOADING = "RECETADIGITAL_LOADING";
export const RECETADIGITAL_CREARRECETA = "RECETADIGITAL_CREARRECETA";
export const RECETADIGITAL_DIAGNOSTICOS = "RECETADIGITAL_DIAGNOSTICOS";
export const RECETADIGITAL_MEDICAMENTOS = "RECETADIGITAL_MEDICAMENTOS";
export const RECETADIGITAL_ERROR = "RECETADIGITAL_ERROR";
export const RECETADIGITAL_RESET = "RECETADIGITAL_RESET";

export const HCDIGIT_LOADING = "HCDIGIT_LOADING";
export const HCDIGIT_PDFOK = "HCDIGIT_PDFOK";
export const HCDIGIT_ERROR = "HCDIGIT_ERROR";
export const HCDIGIT_LISTOK = "HCDIGIT_LISTOK";

export const RESUMENIA_LOADING = "RESUMENIA_LOADING";
export const RESUMENIA_ERROR = "RESUMENIA_ERROR";
export const RESUMENIA_SUCCESS = "RESUMENIA_SUCCESS";
export const RESUMENIA_RESET = "RESUMENIA_RESET";

export const RESET_CONTEXT = "RESET_CONTEXT";
